<?php
/**
 * Created by PhpStorm.
 * User: nata
 * Date: 15/10/18
 * Time: 22:44
 */

require('config.php');

function random_string() {

    $characters = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    $result = '';
    for ($i = 0; $i < 6; $i++)
        $result .= $characters[mt_rand(0, 61)];
    return $result;
}


if (isset($_FILES['user_file']['tmp_name']) && ($_FILES['user_file']['tmp_name'])) {


    /*
     * Upload File.
     *
     * A filename we give an uploaded file should match the following criteria
     *  1) be unique and
     *  2) resistant to enumeration attack
     *
     * To achieve that generate a filename as following:
     *      <id>-<random-6-char-suffix>.jpg
     *
     * Give all uploaded files an extension JPG to simplify the logic a bit,
     * we can do that because a browser doesn't rely on the file extension but analyses
     * an image content and display it accordingly.
     *
     * The procedure:
     *
     * I.   generate a string of 6 random alphanumeric characters
     * II.  insert an image record to db
     * III. get the new image ID generated by DB, this id gives us the uniqueness
     * IV.  move an uploaded file to new location
     * V.   respond with success
     *
     */


    $path = random_string();

    // add media to database
    try {
// Prepare statement
        $stmt = $conn->prepare("
        INSERT INTO media 
          (type, path, creation_date, share_status, description, title, member_id)
        VALUES 
          (:type, :path, now(), :share_status, :description, :title, :member_id)
          ");


        // Create variables for parameters

        //        die(var_dump($_POST));
        $type = 'photo';
//        $creation_date = $_POST['creation_date'];
        $share_status = 'team';
        $description = $_POST['description'];
        $title = isset($_POST['title']) ? $_POST['title'] : '';
        $member_id = 2;


        // Set variables and excecute query
        $stmt->bindParam(':type', $type);
        $stmt->bindParam(':path', $path);
//        $stmt->bindParam(':creation_date', $creation_date);
        $stmt->bindParam(':share_status', $share_status);
        $stmt->bindParam(':description', $description);
        $stmt->bindParam(':title', $title);
        $stmt->bindParam(':member_id', $member_id);
        $stmt->execute();

        // get image ID
        $last_id = $conn->lastInsertId();

        // file destination,
        // filename structure:
        //      <id>-<random-suffic>.jpg
        //
        $dst = './img/' . $last_id . '-' . $path . '.jpg';

        //Move file
        if (!move_uploaded_file($_FILES['user_file']['tmp_name'], $dst)) {
            echo "Something went wrong. Try again!";
        }




    } catch (PDOException $e) {
        echo "Error: " . $e->getMessage();
    }


}


// --------------------------------------- SHOW MEDIA ----------------------------------------------------------------
// Prepare and excecute query
function showmembers($conn)
{

    $stmt = $conn->prepare("SELECT id, type, path, creation_date, share_status, description, title, member_id FROM media");
    $stmt->execute();
    $results = $stmt->fetchAll(PDO::FETCH_ASSOC);
//    die(var_dump($results));



// Echo first part
//    echo '<div class="col-9 float-right"><h5 class="text-muted">Lijst media</h5> <hr><ul class="list-group">';

// Echo rows
    foreach ($results as $row)
    {
        echo '<li class="list-group-item d-flex justify-content-between align-items-center">'
            . $row['id'] . $row['type'] . " / " . $row['path'] . ' ' . $row['creation_date'] . " / " . $row['share_status'] . " / " . $row['description'] . " / " . $row['title'] . " / " . $row['member_id']
            . ' <form class="m-0" action="upload_photo.php" method="post"><input type="hidden" name="deleteid" value="' . $row['id'] . '">'
            . '<input type="submit" name="delete" value="Verwijderen" class="p-1 m-1 btn btn-primary"></form></li>';

    }

// Echo last part
    echo '</li></ul></div>';
}

//$var = $_FILES['user_file']['name'];
//
//echo '<img src=./img/"'  . $var . '"/>';

?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="./img/favicon/android-icon-192x192.png">
    <title>AS'80</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.1/examples/jumbotron/jumbotron.css" rel="stylesheet">
    <link href="style.css" rel="stylesheet">

    <!-- Fontawesome symbols -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <script src="lib/disable_collapse.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        //Laad de 1e pagina
        $(document).ready(function(){
            $('#div1').load('frontpage.php');
        });
    </script>
</head>
<body class="bg-primary">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
    <div class="container">
        <a class="navbar-brand" href="frontpage.php"><img src="img/clublogo2.png" id="logo"/><p>V.V. AS'80</p></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <hr>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="frontpage.php" data-toggle="collapse" data-target="#navbarsExampleDefault"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="./nieuws.php" data-toggle="collapse" data-target="#navbarsExampleDefault"><i class="fas fa-newspaper"></i> Nieuws</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="./media.php" data-toggle="collapse" data-target="#navbarsExampleDefault"><i class="fas fa-video"></i> Media</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="./pool.php" data-toggle="collapse" data-target="#navbarsExampleDefault"><i class="fas fa-car"></i> Carpool</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="./overons.php" data-toggle="collapse" data-target="#navbarsExampleDefault"><i class="fas fa-info-circle"></i> Over ons</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="./contact.php" data-toggle="collapse" data-target="#navbarsExampleDefault"><i class="far fa-envelope"></i> Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <form enctype="multipart/form-data" action="upload_photo.php" method="post">
        <br><br><br><br>
        <input type="file" name="user_file" value="Upload a file"><br><br>
        <!--    проверка, отправилось ли фото на сервер-->
        <input type="hidden" name="action" value="true">
        <input type="text" name="title" value="Title">
        <br><br>
        <textarea rows="4" cols="50" name="description">Describe your photo here...</textarea>
        <br><br>
        <input type="submit" value="Submit">
    </form>
    <br><br>

    <?php showmembers($conn); ?>
    <!--    <!-- 16:9 aspect ratio naar VIDEO Pagina-->
    <!--    <div class="embed-responsive embed-responsive-16by9">-->
    <!--        <iframe class="embed-responsive-item" src="..."></iframe>-->
    <!--    </div>-->

    <footer class="container">
        <p class="text-white">&copy; V.V. AS'80 2018. Alle rechten voorbehouden.</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>
</div>
</body>
</html>





